CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT,
    password VARCHAR(30) NOT NULL,
    kanji_name VARCHAR(30) NOT NULL,
    kata_name VARCHAR(30) NOT NULL,
    position VARCHAR(20) NOT NULL,
    is_superuser BOOLEAN NOT NULL,
    is_approval INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
