CREATE TABLE `user` (
    id INT NOT NULL AUTO_INCREMENT,
    user_name VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(128) NOT NULL,
    kanji_name VARCHAR(30) NOT NULL,
    kata_name VARCHAR(30) NOT NULL,
    position VARCHAR(20) NOT NULL,
    is_superuser BOOLEAN NOT NULL,
    is_approval INT NOT NULL,
    is_active BOOLEAN NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE `office` (
    id INT NOT NULL AUTO_INCREMENT,
    office_name VARCHAR(30) UNIQUE NOT NULL,
    office_id VARCHAR(30) UNIQUE NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE `seat_regist` (
    id INT NOT NULL AUTO_INCREMENT,
    seat_name VARCHAR(30) UNIQUE NOT NULL,
    office_id INT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (office_id) REFERENCES office(id),
    PRIMARY KEY (id)
);

CREATE TABLE `pasokon` (
    id INT NOT NULL AUTO_INCREMENT,
    pasokon_name VARCHAR(30) UNIQUE NOT NULL,
    office_id INT UNIQUE NOT NULL,
    seat_id INT UNIQUE NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (office_id) REFERENCES office(id),
    FOREIGN KEY (seat_id) REFERENCES seat_regist(id),
    PRIMARY KEY (id)
);

CREATE TABLE `seat_reservation` (
    id INT NOT NULL AUTO_INCREMENT,
    reserve_id INT UNIQUE NOT NULL,
    todo_content VARCHAR(128) NOT NULL,
    person_id INT NOT NULL,
    office_id INT NOT NULL,
    seat_id INT NOT NULL,
    start_time DATETIME NOT NULL,
    finish_time DATETIME NOT NULL,
    reserve_day DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (person_id) REFERENCES user(id),
    FOREIGN KEY (seat_id) REFERENCES seat_regist(id),
    PRIMARY KEY (id)
);