version = 5.1.0
archive_dir = /etc/letsencrypt/archive/yoyaku.system-shake-hands.info
cert = /etc/letsencrypt/live/yoyaku.system-shake-hands.info/cert.pem
privkey = /etc/letsencrypt/live/yoyaku.system-shake-hands.info/privkey.pem
chain = /etc/letsencrypt/live/yoyaku.system-shake-hands.info/chain.pem
fullchain = /etc/letsencrypt/live/yoyaku.system-shake-hands.info/fullchain.pem
[renewalparams]
account = 66080e797b152681153d1f8d02585d50
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
yoyaku.system-shake-hands.info = /var/www/certbot
