version: "3"

services:
  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: sample_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      SECRET_KEY: ${SECRET_KEY}
      DB_USER: mysqluser
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: sample_db
      DB_HOST: db
      DB_PORT: 3308
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/log:/var/data/log
    ports:
      - 3308:3308
    command: --port 3308
    tty: true
    networks:
      backend:
        ipv4_address: 172.28.1.5

  api:
    container_name: "api"
    env_file:
      - .env
    build: ./be/api
    ports:
      - "8000:8000"
    volumes:
      - ./be/api:/usr/src/server
    networks:
      backend:
        ipv4_address: 172.28.1.10
    depends_on:
      - db
    
  front:
    container_name: "front"
    env_file:
      - .env
    build: ./fe/front
    ports:
      - "3000:3000"
    volumes:
      - ./fe/front:/usr/src/front
      - /usr/src/front/node_modules
    networks:
      - backend
    depends_on:
      - api

networks:
  backend:
    driver: bridge
    name: app_network
    ipam:
      config:
        - subnet: 172.28.1.0/24